# Generated by Django 5.1.5 on 2025-02-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_recipient_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_see_all_mailing', 'Can see all mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'permissions': [('can_see_all_messages', 'Can see all messages')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'permissions': [('can_see_all_recipients', 'Can see all recipients')], 'verbose_name': 'Получатель', 'verbose_name_plural': 'Получатели'},
        ),
    ]
