# Generated by Django 5.1.5 on 2025-03-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_see_all_mailing', 'Can see all mailing'), ('can_turn_off_mailing', 'Can turn off mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
