# Generated by Django 5.1.5 on 2025-03-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена'), ('Отключена', 'Отключена')], default='Создана', max_length=20, verbose_name='Статус'),
        ),
    ]
